name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - run: |
        cp Gemfile /tmp/
        cd /tmp && bundle install
        mkdir -p _site/${GITHUB_REF##*/}
        bundle exec jekyll clean
        bundle exec jekyll build --baseurl /${env.BRANCH_NAME} --destination _site/${env.BRANCH_NAME} --trace
    