name: KatalonDocsCI
on:
  push:
    branches:
      - test_github_action
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - run: |
        bundle install
        mkdir -p _site/${GITHUB_REF##*/}
        bundle exec jekyll clean
        bundle exec jekyll build --baseurl /${GITHUB_REF##*/} --destination _site/${GITHUB_REF##*/} --trace
    - name: List sites 
      run: |
        pwd
        ls -la 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
          python-version: 2.x
          architecture: x64
    - name: install pip 
      run: |
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
    - name: verify aws cli
      run: |
        aws2 --version
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm install
        aws s3 cp _site/${GITHUB_REF##*/}/ ${{ secrets.AWS_BUCKET_NAME }} -–delete
   
  
