name: KatalonDocsCI
on:
  push:
    branches:
      - test_github_action
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - run: |
        bundle install
        mkdir -p _site/${GITHUB_REF##*/}
        bundle exec jekyll clean
        bundle exec jekyll build --config _config.yml,_config_prod.yml --trace
    - name: List sites 
      run: |
        pwd
        ls -la 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
          python-version: 3.x
          architecture: x64
    - name: install aws 
      run: |
        pip3 install awscli --upgrade --user
    - name: verify aws cli
      run: |
        aws --version
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm install
    - name: Deploy to s3
      run: |
        pwd
        ls -la _sites/
        aws s3 cp --recursive _site/ s3://${{ secrets.AWS_S3_BUCKET }}
   
  
