name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - run: |
        bundle install
        mkdir -p _site/${GITHUB_REF##*/}
        bundle exec jekyll clean
        bundle exec jekyll build --baseurl /${GITHUB_REF##*/} --destination _site/${GITHUB_REF##*/} --trace
    - name: List sites 
      run: |
        pwd
        ls -la 
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
        npm install
        cd _site/${GITHUB_REF##*/}
        node ../deploy.js docs-staging.katalon.com ${GITHUB_REF##*/}"